
package hotelmanagementsys;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Visca
 */
public class Bookings extends javax.swing.JFrame {

    
    
    public Bookings() {
        initComponents();
        GetRooms();
        GetCustomers();
        ShowBookings();
        CostTb.setEditable(false);
    }

    Connection Con=null;
    PreparedStatement Pst=null;
    ResultSet Rs= null,Rs1=null;
    Statement St=null,St1=null;
    private void GetCustomers()
    {
        try{
            Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from Customer");
            while(Rs.next())
            {
                int R = Rs.getInt("CustNum");
                CustomerCb.addItem(String.valueOf(R));  
            }
        }
        catch(Exception e)
        {
            
        }
    }
    int RC;
    private void GetCost()
    {
        try{
            //Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","");
            St1 = Con.createStatement();
            Rs1 = St1.executeQuery("Select Price from RoomTbl where RNum ='"+RoomCb.getSelectedItem().toString()+"'");
            Rs1.next();
            RC= Rs1.getInt(1);
            CostTb.setText(""+RC);
//            while(Rs.next())
//            {
//                int R = Rs.getInt("CustNum");
//                CustomerCb.addItem(String.valueOf(R));  
//            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }
    int Bid;
    private void CountBookings()
    {
        try{
            Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("select Max(BNum) from BookingTbl");
            Rs.next();
            Bid = Rs.getInt(1)+1;
        }
        catch(Exception e)
        {
            
        }
    }
    private void UpdateRooms()
    {
     
        try {
            String s="Booked";
            Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","");
            PreparedStatement Save = Con.prepareStatement("Update RoomTbl set RStatus=? where RNum=?");
            Save.setInt(2,Integer.valueOf(RoomCb.getSelectedItem().toString()));
            Save.setString(1, s);
            int row = Save.executeUpdate();
            JOptionPane.showMessageDialog(this, "Room is Updated!!!");
            Con.close();
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(this, ex);
        }
                
    }
    private void Updatetofree()
    {
     
        try {
            String s="Free";
            Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","");
            PreparedStatement Save = Con.prepareStatement("Update RoomTbl set RStatus=? where RNum=?");
            Save.setInt(2,R);
            Save.setString(1, s);
            int row = Save.executeUpdate();
            JOptionPane.showMessageDialog(this, "Room is Updated!!!");
            Con.close();
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(this, ex);
        }
                
    }
    
    private void GetRooms()
    {
        try{
            String s="Free";
            Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from RoomTbl where RStatus='"+s+"'");
            while(Rs.next())
            {
                int R = Rs.getInt("RNum");
                RoomCb.addItem(String.valueOf(R));  
            }
        }
        catch(Exception e)
        {
            
        }
    }
    private void ShowBookings()
    {
        try{
            Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from BookingTbl");
            BookingList.setModel(DbUtils.resultSetToTableModel(Rs));
            
        }
        catch(Exception e)
        {
            //JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Room = new javax.swing.JLabel();
        Customer = new javax.swing.JLabel();
        booking = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DurationTb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookingList = new javax.swing.JTable();
        CostTb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CustomerCb = new javax.swing.JComboBox<>();
        RoomCb = new javax.swing.JComboBox<>();
        BDate = new com.toedter.calendar.JDateChooser();
        FetchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        Room.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        Room.setForeground(new java.awt.Color(255, 255, 255));
        Room.setText("Rooms");
        Room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomMouseClicked(evt);
            }
        });

        Customer.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        Customer.setForeground(new java.awt.Color(255, 255, 255));
        Customer.setText("Customers");
        Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerMouseClicked(evt);
            }
        });

        booking.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        booking.setForeground(new java.awt.Color(255, 255, 255));
        booking.setText("Bookings");
        booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DashBoard");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(booking)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(Customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Room, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(Room)
                .addGap(18, 18, 18)
                .addComponent(Customer)
                .addGap(18, 18, 18)
                .addComponent(booking)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(138, 138, 138))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Hotel Management System");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Room");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Customer");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Duration in Days");

        DurationTb.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        DurationTb.setForeground(new java.awt.Color(51, 51, 51));
        DurationTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DurationTbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Booking Date");

        AddBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        AddBtn.setText("Book");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        CancelBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Room's Booking");

        BookingList.setBackground(new java.awt.Color(0, 51, 204));
        BookingList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BookingList.setForeground(new java.awt.Color(255, 255, 255));
        BookingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Room", "Customer", "Booking Date", "Duration in Days", "Cost"
            }
        ));
        BookingList.setGridColor(new java.awt.Color(0, 0, 0));
        BookingList.setRowHeight(30);
        BookingList.setRowMargin(3);
        BookingList.setShowGrid(true);
        BookingList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(BookingList);

        CostTb.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        CostTb.setForeground(new java.awt.Color(51, 51, 51));
        CostTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostTbActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Cost");

        CustomerCb.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N

        RoomCb.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        RoomCb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RoomCbItemStateChanged(evt);
            }
        });

        FetchBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        FetchBtn.setForeground(new java.awt.Color(255, 0, 51));
        FetchBtn.setText("Fetch");
        FetchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FetchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                        .addComponent(FetchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CostTb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(CustomerCb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel5)
                                                        .addComponent(DurationTb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(BDate, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(RoomCb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(347, 347, 347))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(397, 397, 397))))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RoomCb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerCb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DurationTb, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(FetchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(CostTb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddBtn)
                            .addComponent(CancelBtn))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void DurationTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DurationTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DurationTbActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here
       if (RoomCb.getSelectedIndex() == -1 || CustomerCb.getSelectedIndex() == -1 || 
    DurationTb.getText().isEmpty() || CostTb.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Missing Data!!!");
} else {
    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String Bdate = sdf.format(BDate.getDate());

        CountBookings(); // Ensure thread-safe implementation
        int roomId = Integer.parseInt(RoomCb.getSelectedItem().toString());
        int customerId = Integer.parseInt(CustomerCb.getSelectedItem().toString());
        int duration = Integer.parseInt(DurationTb.getText());
        int cost = Integer.parseInt(CostTb.getText());

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb", "root", "");
             PreparedStatement save = con.prepareStatement("insert into BookingTbl values(?,?,?,?,?,?)")) {
            save.setInt(1, Bid);
            save.setInt(2, roomId);
            save.setInt(3, customerId);
            save.setString(4, Bdate);
            save.setInt(5, duration);
            save.setInt(6, cost);

            int row = save.executeUpdate();
            JOptionPane.showMessageDialog(this, "Room Booked!!!");

            ShowBookings();
            UpdateRooms();
            RoomCb.removeAllItems();
            GetRooms();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid Data Format!");
    } catch (SQLException ex) {
       // JOptionPane.showMessageDialog(this, "SQL Error: " + ex.getMessage());
    }
}

    }//GEN-LAST:event_AddBtnActionPerformed
int key=0;
    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
         if(key == 0)
        {
            JOptionPane.showMessageDialog(this, "Select a Booking!!!");
        }
        else{
            try {
                Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","");
                PreparedStatement Save = Con.prepareStatement("Delete from BookingTbl where BNum = ?");
                Save.setInt(1,key);
                
                int row = Save.executeUpdate();
                JOptionPane.showMessageDialog(this, "Room is Deleted!!!");
                Con.close();
                ShowBookings();
                Updatetofree();
                RoomCb.removeAllItems();
                GetRooms();
                
                
            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(this,"This fuck");
            }
        }
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void CostTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostTbActionPerformed

    private void RoomCbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RoomCbItemStateChanged
        // TODO add your handling code here:
        GetCost();
    }//GEN-LAST:event_RoomCbItemStateChanged

    private void FetchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FetchBtnActionPerformed
        // TODO add your handling code here:
        int TotAmt;
        TotAmt = RC*Integer.valueOf(DurationTb.getText());
        CostTb.setText(""+TotAmt);
    }//GEN-LAST:event_FetchBtnActionPerformed

    private void RoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomMouseClicked
        // TODO add your handling code here:
        new Rooms().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RoomMouseClicked

    private void bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingMouseClicked
        // TODO add your handling code here:
         new Bookings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bookingMouseClicked

    private void CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseClicked
        // TODO add your handling code here:
         new Customers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CustomerMouseClicked
int R;
    private void BookingListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingListMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)BookingList.getModel(); 
        int Mylndex = BookingList.getSelectedRow(); 
        key = Integer.valueOf(model.getValueAt(Mylndex, 0).toString());
        R=Integer.valueOf(model.getValueAt(Mylndex, 1).toString());
        RoomCb.setSelectedItem(model.getValueAt(Mylndex, 1).toString()); 
        CustomerCb.setSelectedItem(model.getValueAt(Mylndex, 2).toString());
        //BDate.setDate(model.getValueAt(Mylndex, 3).toString());
        DurationTb.setText(model.getValueAt(Mylndex, 4).toString());
        CostTb.setText(model.getValueAt(Mylndex, 5).toString()); 
    }//GEN-LAST:event_BookingListMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new DashBoard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private com.toedter.calendar.JDateChooser BDate;
    private javax.swing.JTable BookingList;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField CostTb;
    private javax.swing.JLabel Customer;
    private javax.swing.JComboBox<String> CustomerCb;
    private javax.swing.JTextField DurationTb;
    private javax.swing.JButton FetchBtn;
    private javax.swing.JLabel Room;
    private javax.swing.JComboBox<String> RoomCb;
    private javax.swing.JLabel booking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoutBtn;
    // End of variables declaration//GEN-END:variables
}
